language: c

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: RID=ubuntu-x64
    - os: linux
      dist: trusty
      sudo: required
      env: RID=centos-x64
    - os: osx
      env: RID=osx

branches:
 only:
   - master

before_install:
 - date -u
 - uname -a
 - env | grep -v "BINTRAY_API_KEY" | sort

install: true

script:
  - if [[ $RID == "osx" ]] || [[ $RID == "ubuntu-x64" ]]; then ./build.libgit2.sh ; fi
  - if [[ $RID != "osx" ]] && [[ $RID != "ubuntu-x64" ]]; then ./dockerbuild.sh   ; fi

after_success: ./uploadbinaries.sh
